// Copyright 2013 Apcera Inc. All rights reserved.

package wsconn

import (
	"io/ioutil"

	"github.com/apcera/cntm-deps/contrail"
)

var (
	// Log may be reassigned by callers of client to include its logs in their output.
	Log contrail.Logger
)

// LogTag is the common context for logs generated by wsconn.
const LogTag = "wsconn"

func init() {
	// Logging is discarded by default.
	// This can be overridden in your code's init method to the log you specify.
	// Here's a super simple example:
	// func init() {
	//   wsconn.Log = YOUR_LOGGER
	// }
	Log = contrail.NewWriter(LogTag, ioutil.Discard)
}
